### ISSUE TITLE
Hovering over a skill makes my client lag

### ISSUE THREAD

**Issue by haladslader** [Mystras-Chosen/MysticMaestro#6]
When i hover over a skill in my action bar it lags, when i disable MysticMaestro it stops happening, ive also noticed it when scrolling through builds in the Hero Architect it does the same thing.

**Comment by anch999** [comment]
Go turn of worldforged tooltips in the options and see if that fixs it and what server are you playing on

**Comment by haladslader** [comment]
Ascension/Area 52 and ill try that now
